python_binary(
    name='create-instance',
    dependencies=['3rdparty/python:boto3'],
    sources=['create_instance.py'],
    compatibility='CPython>=2.7',
    platforms=[
        'macosx-10.12-x86_64',
        'macosx-10.13-x86_64',
        'macosx-10.14-x86_64'
    ],
    shebang='#!/usr/bin/env python'
)